######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 6 15:11:51 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += chartable.h
SOURCES += chartable.cpp main.cpp
