######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 21 08:53:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += qnamredirect.h
SOURCES += main.cpp qnamredirect.cpp
