#! /usr/bin/env python
## This script demonstrates how to build and install
## a simple kde program having KconfigXT settings
## with scons
##
## Thomas Nagy, 2004, 2005

## This file can be reused freely for any project (see COPYING)

############################
## load the config

## Use the environment and the tools set in the top-level
## SConstruct file (set with 'Export') - this is very important

Import( 'env' )

obj=env.qt4obj('program', env)
obj.target='qterm-qt4'
obj.source="""
ui/aboutdialog.ui
ui/addrdialog.ui
ui/articledialog.ui
ui/imageviewer.ui
ui/keydialog.ui
ui/msgdialog.ui
ui/prefdialog.ui
ui/quickdialog.ui
ui/schemadialog.ui
ui/soundconf.ui
ui/sshlogin.ui
ui/zmodemdialog.ui
aboutdialog.cpp
addrdialog.cpp
articledialog.cpp
imageviewer.cpp
keydialog.cpp
main.cpp
msgdialog.cpp
osdmessage.cpp
overlayWidget.cpp
popupMessage.cpp
popwidget.cpp
prefdialog.cpp
progressBar.cpp
qtermbbs.cpp
qtermbuffer.cpp
qtermcanvas.cpp
qtermconfig.cpp
qtermconvert.cpp
qtermdecode.cpp
qtermframe.cpp
qtermhttp.cpp
qtermiplocation.cpp
qtermparam.cpp
qtermpython.cpp
qtermscreen.cpp
qtermsocket.cpp
qtermsound.cpp
qtermtelnet.cpp
qtermtextline.cpp
qtermtimelabel.cpp
qtermtoolbutton.cpp
qtermwindow.cpp
qtermwndmgr.cpp
qtermzmodem.cpp
quickdialog.cpp
schemadialog.cpp
soundconf.cpp
statusBar.cpp
trayicon.cpp
trayicon_mac.cpp
trayicon_win.cpp
trayicon_x11.cpp
zmodemdialog.cpp
ssh/crc32.cpp
ssh/qtermsshauth.cpp
ssh/qtermsshbuffer.cpp
ssh/qtermsshdes.cpp
ssh/qtermsshkex.cpp
ssh/qtermsshlogin.cpp
ssh/qtermsshmd5.cpp
ssh/qtermsshpacket.cpp
ssh/qtermsshrsa.cpp
ssh/qtermsshsession.cpp
ssh/qtermsshsocket.cpp"""
obj.cxxflags='-DQT_THREAD_SUPPORT -DQT3_SUPPORT_WARNINGS'
obj.uselib='QT QTCORE QTGUI QTNETWORK'
obj.libs='ssl'
obj.includes="""
.
ssh
"""
obj.instdir='/usr/bin'
obj.execute()


## This shows how to add custom link flags to the program
#env.QT4addflags_link(['-export-dynamic'])

#############################
## Data to install

## The ui.rc file and the tips go into datadir/appname/
#env.QT4install( 'QT4DATA', 'test1', 'test1ui.rc' )
#env.QT4install( 'QT4DATA', 'test1', 'tips' )

## The kcfg file is installed in a global kcfg directory
#env.QT4install( 'QT4KCFG', '', 'test1.kcfg' )

## Warning : there is a difference between the normal destop file used for the menu
##     and the servicetype desktop file, so they go in different directories
##     you will find more information in 'test3'
#env.QT4install( 'QT4MENU', 'Utilities', 'test1.desktop')

## Use this when you need to install a mimetype file
#env.QT4install( 'QT4MIME', 'application', 'x-test1.desktop' )

